### PR TITLE
Add example tests

### PR DESCRIPTION
**Pull request by gvbhalerao591**

### CODE REVIEW

**Comment by gvbhalerao591** [comment]
adding to tests

**Comment by gvbhalerao591** [comment]
pushing tests

**Review by davidwyld — CHANGES_REQUESTED** [review]
Looking good! Can we remove `.DS_store` from the commit history please and add `.DS_store` to the `.gitignore` file?

**Comment by gvbhalerao591** [comment]
new changes

**Review by davidwyld — APPROVED** [review]

**Pull request merged**
